### ISSUE TITLE
considerMissingDataAsZero not working?

### ISSUE THREAD

**Issue by bumrush** [kamisama/cal-heatmap#114] opened 2014-10-31 00:16 UTC
Hi, I'm playing around with cal-heatmap on [jsfiddle](http://jsfiddle.net/hyperbit/y3pqh9tc/13/). I set `considerMissingDataAsZero` to `true`, but the the grid is still filled in, even when missing values. The only time a cell is empty is when the data is explicitly set to 0. Am I missing anything?

```
var datas = {
    "1414627595": 0,
    "1414713995": 1,
    "1414714007": 10,
    "1414714107": 30,
    "1414914117": 100
}

var calendar = new CalHeatMap();
calendar.init({
    data: datas,
    start: new Date(),
    domain: "month",
    subDomain: "day",
    range: 3,
    legend: [1, 25, 50, 75],
    cellLabel: {
        empty: "No data on {date}",
        filled: "{count} {name} {connector} {date}"
    },
    legendColors: {
        empty: "#eeeeee",
        min: "#5AB5FB",
        max: "#27506E"
    },
    considerMissingDataAsZero: true,
    tooltip: true    
});
```

jsfiddle link: http://jsfiddle.net/hyperbit/y3pqh9tc/13/

**Comment by kamisama** [comment] 2015-01-21 17:22
Closing, duplicate of #117 and #74

**Closed by kamisama** 2015-01-21 17:22 UTC
